---
openapi: "3.0.1"
info:
  title: "Contract for employee roster"
  version: "1"
paths:
  '/employee':
    get:
      summary: "Should be able to get employee"
      responses:
        "200":
          description: "Should be able to get employee"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
              examples:
                200_OKAY:
                  value: '{any}'

components:
  schemas:
    Employee:
      title: Employee
      type: object
      required:
        - id
        - name
        - roster
      properties:
        id:
          type: string
        name:
          type: string
        roster:
          type: array
          items:
            $ref: '#/components/schemas/RosterDate'
    RosterDate:
      title: RosterDate
      type: object
      properties:
        date:
          type: string
        activity:
          type: string